### ISSUE TITLE
Personal data 

### ISSUE THREAD

**Issue by Alexprox7** [kingwang666/GetApk#2]
Is there any personal data in the extracted APK that could link back to your Google Play Store account? As far as I know, it may include some data related to your device resolution and aspect ratio, but does it include any information directly tied to your account? Additionally, how do paid apps prevent themselves from being shared through this extraction method?

**Comment by kingwang666** [comment]
> Is there any personal data in the extracted APK that could link back to your Google Play Store account? As far as I know, it may include some data related to your device resolution and aspect ratio, but does it include any information directly tied to your account? Additionally, how do paid apps prevent themselves from being shared through this extraction method?

I'm using the official API, with no hooks. Therefore, I believe there is no information related to the account in the APK file, as Google should not embed personal information into the APK file. As for paid apps, Google certainly has protection measures in place.
